#!/bin/bash

set -e

oc whoami >/dev/null

for proj in $(oc get projects -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep showroom-); do
  echo $proj

  oc delete pods -l app.kubernetes.io/name=showroom -n $proj --grace-period=0 --force
done

for proj in $(oc get projects -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep showroom-); do
  echo $proj

  oc rollout status deploy/showroom -n $proj --timeout=120s || echo "$(tput setaf 1)Showroom not ready$(tput sgr0)"
done
