apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: Jupyter notebook image with instructlab support
      and minimal dependency set to start experimenting with Jupyter environment.
    opendatahub.io/notebook-image-name: Instructlab
    opendatahub.io/notebook-image-order: "30"
  labels:
    app.kubernetes.io/part-of: workbenches
    app.opendatahub.io/workbenches: "true"
    component.opendatahub.io/name: notebooks
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
  name: instructlab
  namespace: redhat-ods-applications
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version":"3.6"},{"name":"Notebook","version":"6.5"}]'
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.9"}]'
      opendatahub.io/workbench-image-recommended: "true"
    from:
      kind: DockerImage
      name: ghcr.io/kwkoo/minimal-ilab:2023.2
    importPolicy:
      importMode: Legacy
    name: "2023.2"
    referencePolicy:
      type: Source
